---
name: idr0075-cabirol-honeybee/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: no
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split: ;
  # Should this column be included in the clients (yes/no)
  includeclient: yes
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: yes
  # Should empty values be omitted from the client display
  omitempty: yes

columns:

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes

  - name: Characteristics [Age]
    clientname: Age
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/antibody
      columns:
        - name: Experimental Condition [Primary Antibody]
          clientname: Primary Antibody
          include: yes
          omitempty: no
        - name: Primary Antibody Identifier
          clientname: Primary Antibody Identifier
          include: yes
          omitempty: no
        - name: Primary Antibody Identifier
          clientname: Antibody Identifier URL
          clientvalue: http://antibodyregistry.org/{{ value|urlencode }}
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/antibody
      columns:
        - name: Experimental Condition [Secondary Antibody]
          clientname: Secondary Antibody
          include: yes
          omitempty: no
        - name: Secondary Antibody Identifier
          clientname: Secondary Antibody Identifier
          include: yes
          omitempty: no
        - name: Secondary Antibody Identifier
          clientname: Antibody Identifier URL
          clientvalue: http://antibodyregistry.org/{{ value|urlencode }}
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/antibody/supplementary
      columns:
        - name: Primary Antibody Dilution
          clientname: Primary Antibody Dilution
          include: yes
        - name: Secondary Antibody Dilution
          clientname: Secondary Antibody Dilution
          include: yes


advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/antibody
      keys:
        - Antibody Identifier
